import { Box } from "@chakra-ui/react";
import { GetServerSideProps } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "../../app/store";
import { Header } from "../../components/Header";
import { prisma } from "../../app/prisma";
import { useEffect } from "react";
import {
  isPortfolio,
  setCoins,
  setPortfolioName,
  setUserData,
} from "../../app/features/userSlice";
import { PortfolioComponent } from "../../components/Portfolio";
import { ICoin } from "../../app/interfaces/ICoins";
import { IUser } from "../../app/interfaces/IUser";
import { IPortfolio } from "../../app/interfaces/IPortfolio";
import { CreatePortfolio } from "../../components/Portfolio/CreatePortfolio";
import { usePrismaData } from "../../app/hooks/useData";

const Portfolio: React.FC = () => {
  const isPortfolioState = useSelector(
    (state: RootState) => state.portfolio.isPortfolio
  );
  const dispatch = useDispatch();
  const prismaData = usePrismaData();

  useEffect(() => {
    if (prismaData.data?.user) dispatch(setUserData(prismaData.data.user));

    if (prismaData.data?.portfolio && prismaData.data?.portfolio.length > 0) {
      dispatch(isPortfolio(true));
      dispatch(setPortfolioName(prismaData.data.portfolio[0].name));

      if (prismaData.data?.coins && prismaData.data?.coins.length > 0) {
        dispatch(setCoins(prismaData.data.coins));
      }
    }
  }, [prismaData]);

  console.log(prismaData.data);

  return (
    <div>
      <Head>
        <title>Free Crypto Portfolio Tracker | CoinVerseList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box fontFamily="main" fontSize="0.875rem" fontWeight={500}>
        <Header />
        {isPortfolioState ? <PortfolioComponent /> : <CreatePortfolio />}
      </Box>
    </div>
  );
};

export default Portfolio;
